### ISSUE TITLE
ZMQ::LibZMQ2 + fork = Assertion failed: ok (mailbox.cpp:84)

### ISSUE THREAD

**Issue by melo** [lestrrat/p5-ZMQ#11]
Hi,

libzmq 2.2.0 via brew install zeromq, Mac OS X 10.6.8, 10.8.0 and CentOS 6 (repo from http://www.zeromq.org/distro:centos). ZMQ::LibZMQ2 1.01 (latest)

I've opened this first in the ZeroMQ repo (see https://github.com/lestrrat/ZeroMQ-Perl/issues/42) but the problem is also present with ZMQ::LibZMQ2.

I've copied and pasted the description from the other issue here:

Scenario:
- create a context;
- fork;
- in the child, create a new context (no context reuse across processes), plus pub socket;
- in the parent create sub socket; 

At this point both parent and child can exchange messages without any problems. Then:
- in the child send a message, and terminate the process cleanly, making sure we close socket and terminate context;
- the parent gets an assertion failed message: Assertion failed: ok (mailbox.cpp:84)

I can reproduce it perfectly with a small perl script: https://gist.github.com/3416913#file_test_zmq.pl (updated to ZMQ::) but with a similar C program using the libzmq directly I fail to reproduce it.

The exception is shown when the main threads is inside the sleep around line 31, immediately after the child exits. It might be a signals problem, but I don't really know.

The C program that works: https://gist.github.com/3416913#file_test.c

**Comment by viper13** [comment]
Hi,
There is some solution for C++?
